version: '2'

services:
  web:
    image: web
    build:
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      - db
    ports: 
      - "8081:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: alm
      DB_USER: user
      DB_PASSWORD: password

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: alm
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
